### ISSUE TITLE
Upstreaming CoreMP135-Arch project

### ISSUE THREAD

**Issue by dianjixz** [MeemeeLab/CoreMP135-Arch#1]
Can I organize your script into the CoreMP135_buildroot-external-st repository? 
I plan to create a tools directory under CoreMP135_buildroot-external-st to compile various distributions!

**Comment by MeemeeLab** [comment]
Sorry for late reply (I don't really check my inbox), As long as you open source anything derived from my repo, you are free to use it for any purpose!

I'm not very used to buildroot ecosystem, but if you gonna modify my script, my advice is to make sure that package everything that comes into the SD card image, for example linux kernel is packaged as `linux-m5stackcoremp135`.
because Arch Linux users (just like me) are tend to customize their system very often, and may want to build their on kernel and swap existing one, packaged kernels are important for package manager (Arch uses `pacman`) to know what files should be removed or replaced.

Note that my build script uses customized DTS and Kernel.
My Kernel is fork of official Linux not from ST, and drivers are bit modified (e.g. SPI fixes, added AXP2101 driver) to match CoreMP135.
DTS are modified to match my kernel and customized for my liking (e.g. different default serial port, serial port ordering).
You are free to change Kernel and DTS to use stock M5Stack one, freedom of choice is what we all need!

Thanks!

**Comment by MeemeeLab** [comment]
By the way, my Kernel is available at https://github.com/MeemeeLab/linux/commits/m5stack-coremp135/.
Currently ili9342c and AXP2101 backlight driver are pushed, but both drivers available on official SD image provided by buildroot patch (https://github.com/m5stack/CoreMP135_buildroot-external-st/tree/st/2023.02.10/board/m5stack/coremp135/patches/linux)

I have HDMI-TX (LT8618SX), ILI9342C DRM (not FB) driver and AXP2101 poweroff driver already done, but its under testing and not pushed. Some of them still need small modifications. will commit soon if no issues are discovered.

Here's my ~~twitter~~ X post for these drivers:
HDMI-TX: https://x.com/dollychun/status/1792393926068121756
ILI9342C DRM: https://x.com/dollychun/status/1793937358376824932
AXP2101 poweroff: https://x.com/dollychun/status/1803208711428776232

I can make Kernel branch to push testing drivers. If you need driver sources listed here, just tell me and I will make branch for you.

**Comment by dianjixz** [comment]
Thank you very much, I can do it.
